language: python
env:
  global:
  - HUGO_VERSION="0.41"
  - BUCKET_NAME="blog.ricebowljr.cc"
  - MAX_AGE="300"
before_install:
- pip install --upgrade awscli
install:
script:
- wget -qO- "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz" | tar xvz
- ls
- ./hugo
branches:
  only:
  - master
after_success:
- aws s3 sync public/ s3://${BUCKET_NAME}/ --delete --cache-control max-age=${MAX_AGE}
