# Site settings

baseURL = "https://blog.ricebowljr.cc/"
languageCode = "en"
defaultContentLanguage = "en"
title = "RiceBowlJr"

theme = "hugo-base16-theme"

pygmentsUseClassic = true
rssLimit = 10
enableEmoji = true

[author]
  name = "Alexandre Kervadec"
